<div id="help-page">
  <h1>Getting Started</h1>
  <p>Please take a look at our User Guide for the MenuMaker Wordpress plugin. It will walk you through everything you need to know use and customize your Wordpress Menu.</p>
  <p><a href="http://cssmenumaker.com/sites/default/files/wordpressuserguide.pdf" target="_blank" class="button-primary">User Guide</a></p>

  <br><br>

  <h1>Plugin Help</h1>
  <p>We are always looking to gather feedback from our users. If you are having problems using the Plugin, please take a moment to submit a ticket and let us know what problems you are running into.</p>
  <p><a href="http://cssmenumaker.com/wordpress-plugin-support" target="_blank" class="button-primary">Submit Ticket</a></p>

</div>